---
- name: Ansible tags
  hosts: localhost
  gather_facts: false
  tasks:
    - debug:
        msg: "This is first task"
      tags:
        - first
        - general

    - debug:
        msg: "This is second task"
      tags:
        - second
        - always

    - debug:
        msg: "This is third task"
      tags:
        - third
        - general

    - debug:
        msg: "This is fouth task"
      tags:
        - fourth
        - never
